//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication45.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblstudent
    {
        [Required(ErrorMessage ="Required")]
        public int StudentId { get; set; }

        [Required(ErrorMessage = "Required")]
        public string Fullname { get; set; }
        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Required")]
        [MinLength(10,ErrorMessage ="Mobile no should be 10 digit")]
        public string Phone { get; set; }
    }
}
